calculator: calculator.cpp
	g++ -std=c++17 -Wall -o calculator calculator.cpp

reformat: reformat.cpp
	g++ -std=c++17 -Wall -o reformat reformat.cpp

longest_line: longest_line.cpp
	g++ -std=c++17 -Wall -o longest_line longest_line.cpp

